#!/usr/bin/env bash
# write_load.sh — Fire 200 INSERT statements against the PostgreSQL primary
# to generate measurable replication lag on the read replica.
#
# Usage:
#   export PG_PRIMARY_HOST=$(cd .. && terraform output -raw postgres_primary_fqdn)
#   export PGPASSWORD="<your-pg-admin-password>"
#   bash scripts/write_load.sh
#
# While this script runs, query pg_stat_replication on the primary from a
# second terminal to observe live replication lag:
#   psql "host=$PG_PRIMARY_HOST port=5432 user=pgadmin dbname=catalog sslmode=require" \
#     -c "SELECT client_addr, write_lag, flush_lag, replay_lag FROM pg_stat_replication;"

set -euo pipefail

PG_HOST="${PG_PRIMARY_HOST:?Set PG_PRIMARY_HOST to the primary FQDN}"
PG_USER="${PG_USER:-pgadmin}"
PG_DB="${PG_DB:-catalog}"
PG_PORT="${PG_PORT:-5432}"
COUNT=200

CONN="host=${PG_HOST} port=${PG_PORT} user=${PG_USER} dbname=${PG_DB} sslmode=require"

echo "Inserting ${COUNT} rows into products on primary: ${PG_HOST}"
echo "Connect to the primary in another terminal and run:"
echo "  SELECT client_addr, write_lag, flush_lag, replay_lag FROM pg_stat_replication;"
echo ""

for i in $(seq 1 "$COUNT"); do
  psql "$CONN" -c "INSERT INTO products (name, description, price, stock_level)
    VALUES (
      'Load test product $i',
      'Generated by write_load.sh for replication lag measurement',
      $(echo "scale=2; $RANDOM / 100" | bc),
      $((RANDOM % 500))
    );" > /dev/null
  if (( i % 20 == 0 )); then
    echo "  Inserted $i / $COUNT rows..."
  fi
done

echo "Done. Inserted ${COUNT} rows."
echo ""
echo "Run this on the primary to see final replication lag:"
echo "  psql \"$CONN\" -c \"SELECT client_addr, state, write_lag, flush_lag, replay_lag FROM pg_stat_replication;\""
