# write_load.ps1 — Fire 200 INSERT statements against the PostgreSQL primary
# to generate measurable replication lag on the read replica.
#
# Usage (from homeworks/module5/terraform_az/):
#   $env:PG_PRIMARY_HOST = terraform output -raw postgres_primary_fqdn
#   $env:PGPASSWORD      = "<your-pg-admin-password>"
#   .\scripts\write_load.ps1
#
# While this script runs, query pg_stat_replication in a second terminal:
#   psql "host=$($env:PG_PRIMARY_HOST) port=5432 user=pgadmin dbname=catalog sslmode=require" `
#     -c "SELECT client_addr, write_lag, flush_lag, replay_lag FROM pg_stat_replication;"

param(
    [string]$PgHost     = $env:PG_PRIMARY_HOST,
    [string]$PgUser     = $(if ($env:PG_USER) { $env:PG_USER } else { "pgadmin" }),
    [string]$PgDb       = $(if ($env:PG_DB)   { $env:PG_DB   } else { "catalog" }),
    [int]   $PgPort     = 5432,
    [int]   $Count      = 200
)

if (-not $PgHost) {
    Write-Error "Set `$env:PG_PRIMARY_HOST or pass -PgHost."
    exit 1
}

$conn = "host=$PgHost port=$PgPort user=$PgUser dbname=$PgDb sslmode=require"

Write-Host "Inserting $Count rows into products on primary: $PgHost"
Write-Host "Open a second terminal and run:"
Write-Host "  psql `"$conn`" -c `"SELECT client_addr, write_lag, flush_lag, replay_lag FROM pg_stat_replication;`""
Write-Host ""

for ($i = 1; $i -le $Count; $i++) {
    $price = [math]::Round((Get-Random -Minimum 1 -Maximum 999) / 10.0, 2)
    $stock = Get-Random -Minimum 0 -Maximum 500
    $sql = "INSERT INTO products (name, description, price, stock_level) VALUES ('Load test product $i', 'Generated by write_load.ps1 for replication lag measurement', $price, $stock);"
    psql $conn -c $sql | Out-Null
    if ($i % 20 -eq 0) {
        Write-Host "  Inserted $i / $Count rows..."
    }
}

Write-Host ""
Write-Host "Done. Inserted $Count rows."
Write-Host "Run this to see final replication lag:"
Write-Host "  psql `"$conn`" -c `"SELECT client_addr, state, write_lag, flush_lag, replay_lag FROM pg_stat_replication;`""
